POST localhost:9000/items/create
Authorization: Bearer
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

Name of the item

--WebAppBoundary
Content-Disposition: form-data; name="description"

Description of the item

--WebAppBoundary
Content-Disposition: form-data; name="picture"; filename="image.jpg"
Content-Type: image/jpeg

< binary image data >
--WebAppBoundary--
